pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
                steps {
                    script {
                        sh 'pip3 install -r requirements.txt'
                    }
                }
            }

        stage('Run script') {
                steps {
                    script {
                        sh 'python3 getVMInstances_Azure.py'
                        // sh 'cat aws_inventory.ini'
                    }
                }
            }
        }
    }