---
- name: Install Kubernetes
  hosts: your_kubernetes_servers
  become: true

  tasks:
      - name: Add Kubernetes APT repository
        apt_repository:
            repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
            state: present
            update_cache: yes
            filename: kubernetes

      - name: Add Kubernetes GPG key
        shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/kubernetes-archive-keyring.gpg

      - name: Install kubelet, kubeadm, and kubectl
        apt:
            name: "{{ item }}"
            state: present
        loop:
            - kubelet
            - kubeadm
            - kubectl

      - name: Hold kubelet, kubeadm, and kubectl at their current versions
        apt:
            name: "{{ item }}"
            state: held
        loop:
            - kubelet
            - kubeadm
            - kubectl
